#!/bin/bash
# Setup web-ui .env.local from deployment outputs
set -e

echo "🚀 Setting up Web UI environment..."

# Get deployment ID
DEPLOYMENT_ID=$(node -p "require('./deployment-config.json').deploymentId" 2>/dev/null || echo "default")
STACK_NAME="AgentStack-${DEPLOYMENT_ID}"

# Parse flags
FORCE=false
for arg in "$@"; do
    case $arg in
        --force) FORCE=true ;;
    esac
done

# Check if .env.local exists
if [[ -f "web-ui/.env.local" && "$FORCE" == "false" ]]; then
    echo "⚠️  web-ui/.env.local already exists"
    echo "   Run with --force to regenerate"
    exit 0
fi

# Get CDK outputs from CloudFormation
echo "📊 Querying ${STACK_NAME}..."
CDK_OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region us-east-1 --query "Stacks[0].Outputs" --output json 2>/dev/null) || {
    echo "❌ Could not query ${STACK_NAME}. Deploy agent stack first."
    exit 1
}

# Parse CDK outputs
RUNTIME_ARN=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeArn") | .OutputValue // empty')
RUNTIME_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeId") | .OutputValue // empty')
MEMORY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MemoryId") | .OutputValue // empty')
GATEWAY_URL=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayUrl") | .OutputValue // empty')
GATEWAY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayId") | .OutputValue // empty')

# Get Google Maps API key from SSM Parameter Store
echo "📊 Fetching Google Maps API key from SSM..."
GOOGLE_MAPS_API_KEY=$(aws ssm get-parameter --name "/concierge-agent/travel/google-maps-key" --query "Parameter.Value" --with-decryption --output text 2>/dev/null) || GOOGLE_MAPS_API_KEY=""

REGION=${AWS_REGION:-us-east-1}

# Validate required values
if [[ -z "$RUNTIME_ARN" ]]; then
    echo "❌ Missing required values. Ensure agent stack is deployed."
    exit 1
fi

# Generate .env.local
cat > web-ui/.env.local << EOF
# Auto-generated by setup-web-ui-env.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# AWS Configuration
VITE_AWS_REGION=${REGION}

# Agent Runtime Configuration
VITE_AGENT_RUNTIME_ARN=${RUNTIME_ARN}
VITE_AGENT_RUNTIME_ID=${RUNTIME_ID}
VITE_AGENT_ENDPOINT_NAME=DEFAULT

# Memory Configuration
VITE_MEMORY_ID=${MEMORY_ID}

# Gateway Configuration
VITE_GATEWAY_URL=${GATEWAY_URL}
VITE_GATEWAY_ID=${GATEWAY_ID}

# Google Maps API Key
VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
EOF

echo "✅ Created web-ui/.env.local"

if [[ -n "$GOOGLE_MAPS_API_KEY" ]]; then
    echo "✅ Google Maps API key loaded from SSM"
else
    echo "⚠️  Google Maps API key not found in SSM (/concierge-agent/travel/google-maps-key)"
fi

echo ""
echo "Next: cd web-ui && npm run dev"
